-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'USER_REACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'DEAL_ASSIGNED';
ALTER TYPE "AuditAction" ADD VALUE 'PIPELINE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'BILLING_CHANGED';
